app/modules/profile/models.py
from app import db


class UserProfile(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), unique=True, nullable=False)

    orcid = db.Column(db.String(19))
    affiliation = db.Column(db.String(100))
    name = db.Column(db.String(100), nullable=False)
    surname = db.Column(db.String(100), nullable=False)

    def save(self):
        if not self.id:
            db.session.add(self)
        db.session.commit()

app/modules/profile/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length, Regexp, Optional


class UserProfileForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired(), Length(max=100)])
    surname = StringField('Surname', validators=[DataRequired(), Length(max=100)])
    orcid = StringField('ORCID', validators=[
        Optional(),
        Length(min=19, max=19, message='ORCID must have 16 numbers separated by dashes'),
        Regexp(r'^\d{4}-\d{4}-\d{4}-\d{4}$', message='Invalid ORCID format')
    ])
    affiliation = StringField('Affiliation', validators=[
        Optional(),
        Length(min=5, max=100)
    ])
    submit = SubmitField('Save profile')

app/modules/profile/__init__.py
from core.blueprints.base_blueprint import BaseBlueprint

profile_bp = BaseBlueprint('profile', __name__, template_folder='templates')

app/modules/profile/routes.py
from app.modules.auth.services import AuthenticationService
from app.modules.dataset.models import DataSet
from flask import render_template, redirect, url_for, request
from flask_login import login_required, current_user

from app import db
from app.modules.profile import profile_bp
from app.modules.profile.forms import UserProfileForm
from app.modules.profile.services import UserProfileService


@profile_bp.route("/profile/edit", methods=["GET", "POST"])
@login_required
def edit_profile():
    auth_service = AuthenticationService()
    profile = auth_service.get_authenticated_user_profile
    if not profile:
        return redirect(url_for("public.index"))

    form = UserProfileForm()
    if request.method == "POST":
        service = UserProfileService()
        result, errors = service.update_profile(profile.id, form)
        return service.handle_service_response(
            result, errors, "profile.edit_profile", "Profile updated successfully", "profile/edit.html", form
        )

    return render_template("profile/edit.html", form=form)


@profile_bp.route('/profile/summary')
@login_required
def my_profile():
    page = request.args.get('page', 1, type=int)
    per_page = 5

    user_datasets_pagination = db.session.query(DataSet) \
        .filter(DataSet.user_id == current_user.id) \
        .order_by(DataSet.created_at.desc()) \
        .paginate(page=page, per_page=per_page, error_out=False)

    total_datasets_count = db.session.query(DataSet) \
        .filter(DataSet.user_id == current_user.id) \
        .count()

    print(user_datasets_pagination.items)

    return render_template(
        'profile/summary.html',
        user_profile=current_user.profile,
        user=current_user,
        datasets=user_datasets_pagination.items,
        pagination=user_datasets_pagination,
        total_datasets=total_datasets_count
    )

app/modules/profile/templates/profile/edit.html
{% extends "base_template.html" %}

{% block title %}View dataset{% endblock %}

{% block content %}

    <h1 class="h3 mb-3">Edit profile</h1>

    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
          <div class="row">
            <div class="col-12 mb-3">
              <!-- Aquí se elige la clase en función de la categoría del mensaje -->
              <div class="alert alert-{{ category }}" role="alert">
                <div class="alert-message">
                  {% if category == 'success' %}
                    <h4 class="alert-heading"><i class="align-middle" data-feather="check-circle"></i> Success</h4>
                  {% elif category == 'error' %}
                    <h4 class="alert-heading"><i class="align-middle" data-feather="x-circle"></i> Error</h4>
                  {% endif %}
                  <p style="margin-bottom: 0px">{{ message }}</p>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      {% endif %}
    {% endwith %}


    <div class="row">

        <div class="col-12 col-lg-6">

            <form method="POST" action="{{ url_for('profile.edit_profile') }}" class="needs-validation" novalidate>
                {{ form.hidden_tag() }}

                <div class="row form-group">

                    <div class="col-6">
                        {{ form.surname.label(class="form-label") }}
                        {% set surname_value = form.surname.data if form.surname.data else current_user.profile.surname %}
                        {{ form.surname(class="form-control", placeholder="Enter your surname", required=true, value=surname_value) }}
                        {% for error in form.surname.errors %}
                            <span style="color: red;">{{ error }}</span>
                            <br>
                        {% endfor %}
                    </div>

                    <div class="col-6">
                        {{ form.name.label(class="form-label") }}
                        {% set name_value = form.name.data if form.name.data else current_user.profile.name %}
                        {{ form.name(class="form-control", placeholder="Enter your name",
                        required=true, value=name_value) }}
                        {% for error in form.name.errors %}
                            <span style="color: red;">{{ error }}</span>
                            <br>
                        {% endfor %}
                    </div>

                </div>

                <div class="row form-group mt-3">

                    <div class="col-6">
                        {{ form.affiliation.label(class="form-label") }}
                        {% set affiliation_value = form.affiliation.data if form.affiliation.data else (current_user.profile.affiliation  if current_user.profile.affiliation else '') %}
                        {{ form.affiliation(class="form-control", placeholder="Enter your affiliation", required=true, value=affiliation_value) }}
                        {% for error in form.affiliation.errors %}
                            <span style="color: red;">{{ error }}</span>
                            <br>
                        {% endfor %}
                    </div>

                </div>

                <div class="row form-group mt-3">

                    <div class="col-12">
                        {{ form.orcid.label(class="form-label") }}
                        {% set orcid_value = form.orcid.data if form.orcid.data else (current_user.profile.orcid  if current_user.profile.orcid else '') %}
                        {{ form.orcid(class="form-control", placeholder="Enter your ORCID (0000-0123-4567-8901)",
                        required=true, value=orcid_value) }}
                        {% for error in form.orcid.errors %}
                            <span style="color: red;">{{ error }}</span>
                            <br>
                        {% endfor %}
                    </div>

                </div>

                <div class="row form-group">

                    <div class="col-12 mt-3">
                        {{ form.submit(class="btn btn-primary") }}
                    </div>


                </div>
            </form>


        </div>

        <div class="row">

            <div class="col-lg-6 col-12">

                {% if error %}

                    <div class="mt-3">
                        <p style="color: red;"><strong>Error:</strong> {{ error }}
                    </div>

                {% endif %}

            </div>

        </div>

    </div>

{% endblock %}

{% block scripts %}
    <script src="{{ url_for('profile.scripts') }}"></script>
{% endblock %}

app/modules/profile/templates/profile/summary.html
{% extends "base_template.html" %}


{% block title %}User Profile{% endblock %}

{% block content %}

<h1 class="h3 mb-3">User profile</h1>

<div class="row">

    <div class="col-12 col-md-8 col-lg-6"> 

        <div class="card shadow-sm" > 
            <div class="card-header card-dark"> 
                <h5 class="card-title mb-0" style="color: white; font-size: 15px;">Profile Information</h5>
            </div>
            <div class="card-body">
                <p class="card-text h5"><i class="fa fa-user"></i> <strong>Name:</strong> {{user_profile.name}}</p>
                <p class="card-text h5"><i class="fa fa-user-circle"></i> <strong>Surname:</strong> {{user_profile.surname}}</p>
                <p class="card-text h5"><i class="fa fa-building"></i> <strong>Affiliation:</strong> {{user_profile.affiliation}}</p>
                <p class="card-text h5"><i class="fa fa-id-card"></i> <strong>Orcid:</strong> {{user_profile.orcid}}</p>
                <p class="card-text h5"><i class="fa fa-envelope"></i> <strong>Email:</strong> {{user.email}}</p>
                <p class="card-text h5"><i class="fa fa-database"></i> <strong>Uploaded datasets:</strong> {{ total_datasets }} datasets</p>
            </div>
            
        </div>

    </div>

</div>

<h1 class="h3 mb-3">User datasets</h1>

    {% if datasets %}
    <div class="row">
        <div class="col-12">
            <div class="card shadow-sm">
                <div class="card-body">
                    <table class="table table-hover">
                        <thead class="table-light">
                            <tr>
                                <th>Title</th>
                                <th>Publication type</th>
                            </tr>
                        </thead>
                        <tbody>
                          
                            {% for dataset in datasets %}
                            <tr>
                                <td>

                                    {% if dataset.ds_meta_data.dataset_doi %}
                                        <a href="{{ dataset.get_uvlhub_doi() }}">
                                            {{ dataset.ds_meta_data.title }}
                                        </a>
                                    {% else %}
                                        <a href="{{ url_for('dataset.get_unsynchronized_dataset', dataset_id=dataset.id) }}">
                                            {{ dataset.ds_meta_data.title }}
                                        </a>                                    
                                    {% endif %}

                                    
                                </td>
                                <td>{{ dataset.ds_meta_data.publication_type.name.replace('_', ' ').title() }}</td>
                            </tr>
                            {% else %}
                          
                            <tr>
                                <td colspan="2">No datasets uploaded.</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    
   <div class="row">
        <div class="col-12">
            <div class="d-flex justify-content-center mt-4">
                <nav>
                    <ul class="pagination">
                        <li class="page-item {% if not pagination.has_prev %}disabled{% endif %}">
                            <a class="page-link" href="{% if pagination.has_prev %}{{ url_for('profile.my_profile', page=pagination.prev_num) }}{% else %}# {% endif %}" aria-label="Previous">
                                &laquo;
                            </a>
                        </li>
                        {% for num in pagination.iter_pages() %}
                        <li class="page-item {% if num == pagination.page %}active{% endif %}">
                            <a class="page-link" href="{{ url_for('profile.my_profile', page=num) }}">
                                {{ num }}
                            </a>
                        </li>
                        {% endfor %}
                        <li class="page-item {% if not pagination.has_next %}disabled{% endif %}">
                            <a class="page-link" href="{% if pagination.has_next %}{{ url_for('profile.my_profile', page=pagination.next_num) }}{% else %}# {% endif %}" aria-label="Next">
                                &raquo;
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
    {% else %}
    <div class="alert alert-info" role="alert">
        No datasets found
    </div>
    {% endif %}

{% endblock %}

{% block scripts %}
    <script src="{{ url_for('profile.scripts') }}"></script>
{% endblock %}